version: "3.9"
services:
  planner:
    image: cristoflop/planner:latest
    environment:
      - AMQP_USER=guest
      - AMQP_PASS=guest
      - AMQP_HOST=broker
      - AMQP_PORT=5672
      - GRPC_HOST=weather
      - GRPC_PORT=8080
      - TOPO_PORT=8080
      - TOPO_HOST=topo
    depends_on:
      - broker
      - weather
      - topo
  server:
    image: cristoflop/server:latest
    ports:
      - 8080:3000
    environment:
      - AMQP_USER=guest
      - AMQP_PASS=guest
      - AMQP_HOST=broker
      - AMQP_PORT=5672
      - DB_NAME=eoloplants
      - DB_USER=root
      - DB_PORT=3306
      - DB_PASS=root
      - DB_HOST=sql_db
    depends_on:
      - broker
      - sql_db
    command: ["./wait-for-it.sh", "-t", "0", "sql_db:3306", "--", "./wait-for-it.sh", "-t", "0", "broker:5672", "--", "node", "src/server.js"]
  topo:
    image: cristoflop/toposervice:latest
    expose:
      - 8080
    environment:
      - DB_HOST=nosql_db
      - DB_PORT=27017
      - DB_NAME=topo_db
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      - nosql_db
  weather:
    image: cristoflop/weatherservice:latest
    expose:
      - 8080
    environment:
      - GRPC_HOST=weather
      - GRPC_PORT=8080
  sql_db:
    image: mysql:8.0.23
    environment:
      - MYSQL_DATABASE=eoloplants
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
    volumes:
      - ./mysql:/var/lib/mysql
  nosql_db:
    image: mongo:4.2.12-bionic
    environment:
      - MONGO_INITDB_DATABASE=topo_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    expose:
      - 27017
    volumes:
      - ./mongo:/data/db
  broker:
    image: rabbitmq:3.8.14-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    expose:
      - 5672
    volumes:
      - ./broker:/var/lib/rabbitmq