version: "3.9"
services:
  sql_db:
    image: mysql:8.0.23
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
  nosql_db:
    image: mongo:4.2.12-bionic
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
  broker:
    image: rabbitmq:3.8.14-management-alpine
    env_file: .env
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./broker:/var/lib/rabbitmq