{{- if .Values.config.createPersistenceVolumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-{{ .Release.Name }}
spec:
  storageClassName: mysql
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /db/mysql
---
{{- end }}