---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-{{ .Release.Name }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dns-egress-{{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      dns-policy: enabled
  egress:
    - ports:
        {{- range .Values.egress.ports }}
        - port: {{ .port }}
          protocol: {{ .protocol }}
        {{- end }}
---