{{- if .Values.config.createPersistenceVolumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-{{ .Release.Name }}
spec:
  storageClassName: mongodb
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /db/mongo
---
{{- end }}