---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy-{{ .Release.Name }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rabbitmq-{{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-{{ .Release.Name }}
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            {{- range .Values.rabbitmq.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
          {{- end }}
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - mountPath: /var/lib/rabbitmq/mnesia
              name: datarabbit
      volumes:
        - name: datarabbit
          persistentVolumeClaim:
            claimName: rabbit-pvc-{{ .Release.Name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-pvc-{{ .Release.Name }}
spec:
  {{- if .Values.config.createPersistenceVolumes }}
  storageClassName: {{ "rabbit" }}
  {{ else }}
  storageClassName: {{ .Values.rabbitmq.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service-{{ .Release.Name }}
  labels:
    app: rabbitmq-{{ .Release.Name }}
spec:
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: rabbitmq-port-5672
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: rabbitmq-port-15672
  selector:
    app: rabbitmq-{{ .Release.Name }}
  type: ClusterIP
---
  {{- if .Values.config.enableNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rabbitmq-from-planner-server-{{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: rabbitmq-{{ .Release.Name }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: planner-{{ .Release.Name }}
        - podSelector:
            matchLabels:
              app: server-{{ .Release.Name }}
      ports:
        - port: 5672
          protocol: TCP
---
  {{- end }}