---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherservice-deploy-{{ .Release.Name }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: weatherservice-{{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: weatherservice-{{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
        - name: weatherservice-{{ .Release.Name }}
          image: {{ .Values.weatherservice.image }}:{{ .Values.weatherservice.tag }}
          env:
            - name: GRPC_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- range .Values.weatherservice.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
          {{- end }}
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: weatherservice-service-{{ .Release.Name }}
  labels:
    app: weatherservice-{{ .Release.Name }}
spec:
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: weatherservice-port
  selector:
    app: weatherservice-{{ .Release.Name }}
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: weather-from-planner-{{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: weatherservice-{{ .Release.Name }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: planner-{{ .Release.Name }}
      ports:
        - port: 9090
          protocol: TCP
