version: "3.0"
services:
  planner:
    image: cristoflop/planner:latest
    expose:
      - 8080
    environment:
      - AMQP_USER=guest
      - AMQP_PASS=guest
      - AMQP_HOST=broker
      - AMQP_PORT=5672
      - GRPC_HOST=weather
      - GRPC_PORT=8080
      - TOPO_PORT=8080
      - TOPO_HOST=topo
    depends_on:
      - broker
      - weather
      - topo
  server:
    image: cristoflop/server:latest
    ports:
      - 8080:3000
    environment:
      - AMQP_USER=guest
      - AMQP_PASS=guest
      - AMQP_HOST=broker
      - AMQP_PORT=5672
      - DB_NAME=eoloplants
      - DB_USER=root
      - DB_PORT=3306
      - DB_PASS=root
      - DB_HOST=sqldb
    labels:
      kompose.service.type: nodeport
    depends_on:
      - broker
      - sqldb
    command: ["./wait-for-it.sh", "-t", "0", "sqldb:3306", "--", "./wait-for-it.sh", "-t", "0", "broker:5672", "--", "node", "src/server.js"]
  topo:
    image: cristoflop/toposervice:latest
    expose:
      - 8080
    environment:
      - SERVER_PORT=8080
      - NOSQL_DB_HOST=nosqldb
      - NOSQL_DB_PORT=27017
      - NOSQL_DB_NAME=topodb
      - NOSQL_DB_USER=root
      - NOSQL_DB_PASS=root
    depends_on:
      - nosqldb
  weather:
    image: cristoflop/weatherservice:latest
    expose:
      - 8080
    environment:
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=8080
  sqldb:
    image: mysql:8.0.23
    environment:
      - MYSQL_DATABASE=eoloplants
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
  nosqldb:
    image: mongo:4.2.12-bionic
    environment:
      - MONGO_INITDB_DATABASE=topodb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    expose:
      - 27017
  broker:
    image: rabbitmq:3.8.14-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    expose:
      - 5672