{{- range .Values.images }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eolicplants.fullname" $ }}-{{ .name }}
  labels:
    {{- include "eolicplants.labels" $ | nindent 4 }}
    release: {{ $.Release.Name }}
spec:
  {{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
  {{- include "eolicplants.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
      {{- toYaml $ | nindent 8 }}
      {{- end }}
      labels:
    {{- include "eolicplants.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml $ | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eolicplants.serviceAccountName" $ }}
      securityContext:
      {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- range .volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
      {{- end }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
          {{- toYaml $.Values.securityContext | nindent 12 }}
          env:
            {{- range $key, $value := .env}}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .pullPolicy }}
          volumeMounts:
            {{- range .volumes }}
            - mountPath: {{ .path }}
              name: {{ .name }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
      {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
      {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
      {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
      {{- toYaml $ | nindent 8 }}
  {{- end }}
---
  {{- end }}