{{- if .Values.volumes.enabled }}
{{- range $key, $value := .Values.volumes.items }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $key }}-pvc-sc
spec:
  {{- if $value.storageClassName }}
  storageClassName: {{ $value.storageClassName }}
  {{- end }}
  accessModes:
  {{- range $value.accessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ $value.size }}
---
{{- end }}
{{- end }}