---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planner-deploy-{{ .Release.Name }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: planner-{{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: planner-{{ .Release.Name }}
        dns-policy: enabled
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
        - name: planner-{{ .Release.Name }}
          image: {{ .Values.planner.image }}:{{ .Values.planner.tag }}
          env:
            {{- range .Values.mysqldb.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
  {{- end }}
---
  {{- if .Values.config.enableNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: planner-to-rabbit-weather-topo-{{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: planner-{{ .Release.Name }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: rabbitmq-{{ .Release.Name }}
      ports:
        - port: 5672
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: weatherservice-{{ .Release.Name }}
      ports:
        - port: 9090
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: toposervice-{{ .Release.Name }}
      ports:
        - port: 8080
          protocol: TCP
  {{- end }}
---